"""
Sample Superstore Sales Report Generator

Reads the Sample Superstore CSV, cleans it, computes summary metrics,
renders charts, and writes a one-page PDF report to ./output/.
"""

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

ROOT = Path(__file__).parent
INPUT_CSV = ROOT / "SampleSuperstore.csv"
OUTPUT_DIR = ROOT / "output"
CHART_PATH = OUTPUT_DIR / "sales_by_category.png"
PDF_PATH = OUTPUT_DIR / "superstore_report.pdf"


def load_and_clean(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, encoding="latin1")
    df.columns = [c.strip() for c in df.columns]
    df = df.drop_duplicates()
    df = df.dropna(subset=["Sales", "Profit", "Category"])
    df["Sales"] = df["Sales"].astype(float)
    df["Profit"] = df["Profit"].astype(float)
    return df


def summarize(df: pd.DataFrame) -> dict:
    return {
        "rows": len(df),
        "total_sales": df["Sales"].sum(),
        "total_profit": df["Profit"].sum(),
        "avg_discount": df["Discount"].mean(),
        "profit_margin": df["Profit"].sum() / df["Sales"].sum(),
    }


def render_chart(df: pd.DataFrame, out_path: Path) -> None:
    by_cat = df.groupby("Category", as_index=False)["Sales"].sum().sort_values("Sales", ascending=False)
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(by_cat["Category"], by_cat["Sales"], color="#2E86AB")
    ax.set_title("Total Sales by Category")
    ax.set_ylabel("Sales (USD)")
    ax.set_xlabel("Category")
    ax.grid(axis="y", linestyle="--", alpha=0.4)
    for i, v in enumerate(by_cat["Sales"]):
        ax.text(i, v, f"${v:,.0f}", ha="center", va="bottom", fontsize=9)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def build_region_table(df: pd.DataFrame) -> list[list[str]]:
    agg = (
        df.groupby("Region")
        .agg(Sales=("Sales", "sum"), Profit=("Profit", "sum"), Orders=("Sales", "count"))
        .sort_values("Sales", ascending=False)
        .reset_index()
    )
    rows = [["Region", "Sales", "Profit", "Orders"]]
    for _, r in agg.iterrows():
        rows.append([
            r["Region"],
            f"${r['Sales']:,.0f}",
            f"${r['Profit']:,.0f}",
            f"{int(r['Orders']):,}",
        ])
    return rows


def render_pdf(df: pd.DataFrame, summary: dict, chart_path: Path, pdf_path: Path) -> None:
    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(
        str(pdf_path),
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Sample Superstore — Sales Report", styles["Title"]))
    story.append(Spacer(1, 0.4 * cm))
    story.append(Paragraph("Generated by automation demo (Python + pandas + reportlab).", styles["Italic"]))
    story.append(Spacer(1, 0.6 * cm))

    kpi_rows = [
        ["Metric", "Value"],
        ["Rows", f"{summary['rows']:,}"],
        ["Total Sales", f"${summary['total_sales']:,.2f}"],
        ["Total Profit", f"${summary['total_profit']:,.2f}"],
        ["Profit Margin", f"{summary['profit_margin']:.1%}"],
        ["Average Discount", f"{summary['avg_discount']:.1%}"],
    ]
    kpi_table = Table(kpi_rows, hAlign="LEFT", colWidths=[5 * cm, 5 * cm])
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2E86AB")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("ALIGN", (1, 1), (1, -1), "RIGHT"),
    ]))
    story.append(kpi_table)
    story.append(Spacer(1, 0.6 * cm))

    story.append(Paragraph("Sales by Category", styles["Heading2"]))
    story.append(Image(str(chart_path), width=15 * cm, height=8.5 * cm))
    story.append(Spacer(1, 0.6 * cm))

    story.append(Paragraph("Performance by Region", styles["Heading2"]))
    region_rows = build_region_table(df)
    region_table = Table(region_rows, hAlign="LEFT", colWidths=[3.5 * cm, 3.5 * cm, 3.5 * cm, 3.5 * cm])
    region_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2E86AB")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
    ]))
    story.append(region_table)

    doc.build(story)


def main() -> None:
    df = load_and_clean(INPUT_CSV)
    summary = summarize(df)
    render_chart(df, CHART_PATH)
    render_pdf(df, summary, CHART_PATH, PDF_PATH)
    print(f"Rows processed: {summary['rows']:,}")
    print(f"Total Sales:    ${summary['total_sales']:,.2f}")
    print(f"Total Profit:   ${summary['total_profit']:,.2f}")
    print(f"Profit Margin:  {summary['profit_margin']:.1%}")
    print(f"Chart written:  {CHART_PATH}")
    print(f"PDF written:    {PDF_PATH}")


if __name__ == "__main__":
    main()
